//------------------------------------------------------------------------------
// <auto-generated>
//     Manual designer companion for Strings.resx
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace DisplayForge.Resources
{
    using System.Globalization;
    using System.Resources;

    public static class Strings
    {
        private static ResourceManager? _resourceManager;
        private static CultureInfo? _resourceCulture;

        public static ResourceManager ResourceManager =>
            _resourceManager ??= new ResourceManager("DisplayForge.Resources.Strings", typeof(Strings).Assembly);

        public static CultureInfo? Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string Get(string name) =>
            ResourceManager.GetString(name, _resourceCulture) ?? name;

        public static string AppName => Get("AppName");
        public static string Profiles => Get("Profiles");
        public static string CurrentMonitors => Get("CurrentMonitors");
        public static string ProfileMonitors => Get("ProfileMonitors");
        public static string NewProfile => Get("NewProfile");
        public static string SaveToProfile => Get("SaveToProfile");
        public static string Apply => Get("Apply");
        public static string Duplicate => Get("Duplicate");
        public static string Delete => Get("Delete");
        public static string Rename => Get("Rename");
        public static string Hotkey => Get("Hotkey");
        public static string ClearHotkey => Get("ClearHotkey");
        public static string Settings => Get("Settings");
        public static string ShowMainWindow => Get("ShowMainWindow");
        public static string Exit => Get("Exit");
        public static string Language => Get("Language");
        public static string LanguageAuto => Get("LanguageAuto");
        public static string StartMinimized => Get("StartMinimized");
        public static string ShowNotifications => Get("ShowNotifications");
        public static string HotkeysEnabled => Get("HotkeysEnabled");
        public static string ConfirmApplySection => Get("ConfirmApplySection");
        public static string ConfirmApplyFromUi => Get("ConfirmApplyFromUi");
        public static string ConfirmApplyFromHotkey => Get("ConfirmApplyFromHotkey");
        public static string ConfirmApplyTimeoutSeconds => Get("ConfirmApplyTimeoutSeconds");
        public static string Save => Get("Save");
        public static string Cancel => Get("Cancel");
        public static string StatusReady => Get("StatusReady");
        public static string StatusApplied => Get("StatusApplied");
        public static string StatusFailed => Get("StatusFailed");
        public static string StatusSaved => Get("StatusSaved");
        public static string StatusDeleted => Get("StatusDeleted");
        public static string ConfirmDelete => Get("ConfirmDelete");
        public static string ConfirmDeleteTitle => Get("ConfirmDeleteTitle");
        public static string HotkeyConflict => Get("HotkeyConflict");
        public static string HotkeyRegisterFailed => Get("HotkeyRegisterFailed");
        public static string HotkeyHint => Get("HotkeyHint");
        public static string Name => Get("Name");
        public static string Primary => Get("Primary");
        public static string Enabled => Get("Enabled");
        public static string Resolution => Get("Resolution");
        public static string Width => Get("Width");
        public static string Height => Get("Height");
        public static string Refresh => Get("Refresh");
        public static string RefreshMonitors => Get("RefreshMonitors");
        public static string Position => Get("Position");
        public static string PosX => Get("PosX");
        public static string PosY => Get("PosY");
        public static string Orientation => Get("Orientation");
        public static string NoProfileSelected => Get("NoProfileSelected");
        public static string TrayTooltip => Get("TrayTooltip");
        public static string AlreadyRunning => Get("AlreadyRunning");
        public static string NewProfileName => Get("NewProfileName");
        public static string MissingMonitors => Get("MissingMonitors");
        public static string CloseToTray => Get("CloseToTray");
        public static string ConfirmKeepSettingsTitle => Get("ConfirmKeepSettingsTitle");
        public static string ConfirmKeepSettingsMessage => Get("ConfirmKeepSettingsMessage");
        public static string ConfirmKeepSettingsCountdown => Get("ConfirmKeepSettingsCountdown");
        public static string KeepChanges => Get("KeepChanges");
        public static string RevertChanges => Get("RevertChanges");
        public static string StatusReverted => Get("StatusReverted");
        public static string StatusRevertFailed => Get("StatusRevertFailed");
        public static string LayoutEditor => Get("LayoutEditor");
        public static string LayoutEditorHint => Get("LayoutEditorHint");
        public static string LayoutEditorEmpty => Get("LayoutEditorEmpty");
        public static string IdentifyMonitors => Get("IdentifyMonitors");
        public static string IdentifyMonitorsHint => Get("IdentifyMonitorsHint");
        public static string StatusIdentifyShown => Get("StatusIdentifyShown");
        public static string AppTagline => Get("AppTagline");
        public static string SelectedProfileSection => Get("SelectedProfileSection");
        public static string ProfileMonitorsHint => Get("ProfileMonitorsHint");
        public static string NewProfileHint => Get("NewProfileHint");
        public static string SaveToProfileHint => Get("SaveToProfileHint");
        public static string ApplyHint => Get("ApplyHint");
        public static string RenamePrompt => Get("RenamePrompt");
        public static string GeneralSection => Get("GeneralSection");
        public static string ConfirmApplyHint => Get("ConfirmApplyHint");
        public static string OrientationLandscape => Get("OrientationLandscape");
        public static string OrientationPortrait => Get("OrientationPortrait");
        public static string OrientationLandscapeFlipped => Get("OrientationLandscapeFlipped");
        public static string OrientationPortraitFlipped => Get("OrientationPortraitFlipped");
        public static string EmptyStateNoProfiles => Get("EmptyStateNoProfiles");
        public static string AppliedBadge => Get("AppliedBadge");
    }
}
