name: Spell Check

on:
  push:
    branches: [main]
    paths:
      - "**.md"
      - "**.txt"
      - "**.yml"
      - "**.yaml"
      - ".typos.toml"
  pull_request:
    paths:
      - "**.md"
      - "**.txt"
      - "**.yml"
      - "**.yaml"
      - ".typos.toml"

permissions:
  contents: read

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Check spelling
        uses: crate-ci/typos@v1.48.0
        with:
          config: .typos.toml
